//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InQuiryResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InQuiryResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.InQuiryResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to change status to &quot;Empty&quot; ?.
        /// </summary>
        internal static string TCFC021F03 {
            get {
                return ResourceManager.GetString("TCFC021F03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack quantity must be more than zero !.
        /// </summary>
        internal static string TCFC034F01 {
            get {
                return ResourceManager.GetString("TCFC034F01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inputted product code and pre-product lot-no is duplicated !.
        /// </summary>
        internal static string TCFC036F04 {
            get {
                return ResourceManager.GetString("TCFC036F04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inputted pallet-seqno is duplicated !.
        /// </summary>
        internal static string TCFC037F02 {
            get {
                return ResourceManager.GetString("TCFC037F02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value of stocked pallets !.
        /// </summary>
        internal static string TCFC038F01 {
            get {
                return ResourceManager.GetString("TCFC038F01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one line must be valid, please input data !.
        /// </summary>
        internal static string TCSS000018 {
            get {
                return ResourceManager.GetString("TCSS000018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This pallet is being used !.
        /// </summary>
        internal static string TCSS000024 {
            get {
                return ResourceManager.GetString("TCSS000024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find details with this shelf no !.
        /// </summary>
        internal static string TCSS000041 {
            get {
                return ResourceManager.GetString("TCSS000041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is out of range !.
        /// </summary>
        internal static string TCSS000042 {
            get {
                return ResourceManager.GetString("TCSS000042", resourceCulture);
            }
        }
    }
}
