//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MaterialResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MaterialResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MaterialResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can’t leave this field blank..
        /// </summary>
        internal static string MSG1 {
            get {
                return ResourceManager.GetString("MSG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraction cannot be more than the packing unit!.
        /// </summary>
        internal static string MSG14 {
            get {
                return ResourceManager.GetString("MSG14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conveyor status error!.
        /// </summary>
        internal static string MSG15 {
            get {
                return ResourceManager.GetString("MSG15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse status error!.
        /// </summary>
        internal static string MSG16 {
            get {
                return ResourceManager.GetString("MSG16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquid Class error!.
        /// </summary>
        internal static string MSG17 {
            get {
                return ResourceManager.GetString("MSG17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no empty location available in the warehouse now!.
        /// </summary>
        internal static string MSG18 {
            get {
                return ResourceManager.GetString("MSG18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet No. error!.
        /// </summary>
        internal static string MSG28 {
            get {
                return ResourceManager.GetString("MSG28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to restore?.
        /// </summary>
        internal static string MSG29 {
            get {
                return ResourceManager.GetString("MSG29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same record exists in database..
        /// </summary>
        internal static string MSG3 {
            get {
                return ResourceManager.GetString("MSG3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The corresponding conveyor does not exist!.
        /// </summary>
        internal static string MSG34 {
            get {
                return ResourceManager.GetString("MSG34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelf No [“ + [As_ConvCode] + “  + [As_DestConvCode] “] moving …&quot;.
        /// </summary>
        internal static string MSG35 {
            get {
                return ResourceManager.GetString("MSG35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no empty location available in the warehouse now!.
        /// </summary>
        internal static string MSG37 {
            get {
                return ResourceManager.GetString("MSG37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This material is in stock.  Data cannot be deleted!.
        /// </summary>
        internal static string MSG4 {
            get {
                return ResourceManager.GetString("MSG4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The retrieval quantity cannot be more than the possible retrieval quantity!.
        /// </summary>
        internal static string MSG40 {
            get {
                return ResourceManager.GetString("MSG40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to retrieve?.
        /// </summary>
        internal static string MSG41 {
            get {
                return ResourceManager.GetString("MSG41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack quantity must be more than zero!.
        /// </summary>
        internal static string MSG42 {
            get {
                return ResourceManager.GetString("MSG42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected quantity is less than in-stock quantity!.
        /// </summary>
        internal static string MSG5 {
            get {
                return ResourceManager.GetString("MSG5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P. O. No. or Partial Delivery or material code is not corresponding!.
        /// </summary>
        internal static string MSG7 {
            get {
                return ResourceManager.GetString("MSG7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material lot-no cannot be empty!.
        /// </summary>
        internal static string MSG8 {
            get {
                return ResourceManager.GetString("MSG8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack quantity must be more than zero!.
        /// </summary>
        internal static string MSG9 {
            get {
                return ResourceManager.GetString("MSG9", resourceCulture);
            }
        }
    }
}
