//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PreProductManagementResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PreProductManagementResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PreProductManagementResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find corresponding record in the Database..
        /// </summary>
        internal static string MSG1 {
            get {
                return ResourceManager.GetString("MSG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This container is in stock..
        /// </summary>
        internal static string MSG12 {
            get {
                return ResourceManager.GetString("MSG12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conveyor status error!.
        /// </summary>
        internal static string MSG13 {
            get {
                return ResourceManager.GetString("MSG13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse status error!.
        /// </summary>
        internal static string MSG14 {
            get {
                return ResourceManager.GetString("MSG14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A message is being received, please wait..
        /// </summary>
        internal static string MSG15 {
            get {
                return ResourceManager.GetString("MSG15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no empty container in stock..
        /// </summary>
        internal static string MSG21 {
            get {
                return ResourceManager.GetString("MSG21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no empty location available in the warehouse now..
        /// </summary>
        internal static string MSG24 {
            get {
                return ResourceManager.GetString("MSG24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input tablet line does not match the data in the Database..
        /// </summary>
        internal static string MSG26 {
            get {
                return ResourceManager.GetString("MSG26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This record was modified by others, please retry..
        /// </summary>
        internal static string MSG28 {
            get {
                return ResourceManager.GetString("MSG28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No completed kneading found !.
        /// </summary>
        internal static string MSG32 {
            get {
                return ResourceManager.GetString("MSG32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack quantity must be more than zero..
        /// </summary>
        internal static string MSG6 {
            get {
                return ResourceManager.GetString("MSG6", resourceCulture);
            }
        }
    }
}
