//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProductManagementResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductManagementResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ProductManagementResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find corresponding records from database!.
        /// </summary>
        internal static string MSG1 {
            get {
                return ResourceManager.GetString("MSG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The corresponding conveyor does not exist!.
        /// </summary>
        internal static string MSG10 {
            get {
                return ResourceManager.GetString("MSG10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This pallet is being used!.
        /// </summary>
        internal static string MSG11 {
            get {
                return ResourceManager.GetString("MSG11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The corresponding pallet is out of the warehouse and the data is valid, Ok to store with it?.
        /// </summary>
        internal static string MSG12 {
            get {
                return ResourceManager.GetString("MSG12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one line must be valid, please input data!.
        /// </summary>
        internal static string MSG13 {
            get {
                return ResourceManager.GetString("MSG13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack quantity must be more than zero!.
        /// </summary>
        internal static string MSG14 {
            get {
                return ResourceManager.GetString("MSG14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraction cannot be more than the packing unit!.
        /// </summary>
        internal static string MSG15 {
            get {
                return ResourceManager.GetString("MSG15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraction cannot be bigger than left fraction!.
        /// </summary>
        internal static string MSG16 {
            get {
                return ResourceManager.GetString("MSG16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack Qty is greater than pack available!.
        /// </summary>
        internal static string MSG17 {
            get {
                return ResourceManager.GetString("MSG17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to store?.
        /// </summary>
        internal static string MSG18 {
            get {
                return ResourceManager.GetString("MSG18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no empty location available in the warehouse now!.
        /// </summary>
        internal static string MSG19 {
            get {
                return ResourceManager.GetString("MSG19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected product&apos;s attribute is different from the checkbox &quot;out-of-spec&quot;!.
        /// </summary>
        internal static string MSG2 {
            get {
                return ResourceManager.GetString("MSG2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to delete?.
        /// </summary>
        internal static string MSG20 {
            get {
                return ResourceManager.GetString("MSG20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same record exists in database!.
        /// </summary>
        internal static string MSG21 {
            get {
                return ResourceManager.GetString("MSG21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to add?.
        /// </summary>
        internal static string MSG22 {
            get {
                return ResourceManager.GetString("MSG22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you make sure this product is &quot;Certification Ok&quot;?.
        /// </summary>
        internal static string MSG23 {
            get {
                return ResourceManager.GetString("MSG23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you make sure this product is &quot;Certification NG&quot;?.
        /// </summary>
        internal static string MSG24 {
            get {
                return ResourceManager.GetString("MSG24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date is later than end date!.
        /// </summary>
        internal static string MSG25 {
            get {
                return ResourceManager.GetString("MSG25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to print?.
        /// </summary>
        internal static string MSG26 {
            get {
                return ResourceManager.GetString("MSG26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input request shipping quantity is error!.
        /// </summary>
        internal static string MSG27 {
            get {
                return ResourceManager.GetString("MSG27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to update?.
        /// </summary>
        internal static string MSG28 {
            get {
                return ResourceManager.GetString("MSG28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to assign?.
        /// </summary>
        internal static string MSG29 {
            get {
                return ResourceManager.GetString("MSG29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you make sure the products which will be stored on this pallet are &quot;out-of-spec storage&quot;?.
        /// </summary>
        internal static string MSG3 {
            get {
                return ResourceManager.GetString("MSG3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not matched pallet!.
        /// </summary>
        internal static string MSG30 {
            get {
                return ResourceManager.GetString("MSG30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping product will be shipped from retrieved product and in-stock product!.
        /// </summary>
        internal static string MSG31 {
            get {
                return ResourceManager.GetString("MSG31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping product will be shipped from retrieved product!.
        /// </summary>
        internal static string MSG32 {
            get {
                return ResourceManager.GetString("MSG32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to retrieve?.
        /// </summary>
        internal static string MSG33 {
            get {
                return ResourceManager.GetString("MSG33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to de-assign?.
        /// </summary>
        internal static string MSG34 {
            get {
                return ResourceManager.GetString("MSG34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to transfer between floors?.
        /// </summary>
        internal static string MSG35 {
            get {
                return ResourceManager.GetString("MSG35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelf No is moving….
        /// </summary>
        internal static string MSG36 {
            get {
                return ResourceManager.GetString("MSG36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must be inputted!.
        /// </summary>
        internal static string MSG37 {
            get {
                return ResourceManager.GetString("MSG37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The max loading number does not exist!.
        /// </summary>
        internal static string MSG38 {
            get {
                return ResourceManager.GetString("MSG38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loading pallet number must be less than max loading number!.
        /// </summary>
        internal static string MSG39 {
            get {
                return ResourceManager.GetString("MSG39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you make sure the products which will be stored on this pallet are &quot;normal storage&quot;?.
        /// </summary>
        internal static string MSG4 {
            get {
                return ResourceManager.GetString("MSG4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The retrieval quantity cannot be more than the possible retrieval quantity!.
        /// </summary>
        internal static string MSG40 {
            get {
                return ResourceManager.GetString("MSG40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input product code and pre-product lot-no is duplicated by other product!.
        /// </summary>
        internal static string MSG41 {
            get {
                return ResourceManager.GetString("MSG41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned quantity is not enough!.
        /// </summary>
        internal static string MSG42 {
            get {
                return ResourceManager.GetString("MSG42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request retrieval quantity is error!.
        /// </summary>
        internal static string MSG43 {
            get {
                return ResourceManager.GetString("MSG43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input lot-no is error!.
        /// </summary>
        internal static string MSG44 {
            get {
                return ResourceManager.GetString("MSG44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input pallet-no is error!.
        /// </summary>
        internal static string MSG45 {
            get {
                return ResourceManager.GetString("MSG45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is some product in the pallet, do you want to continue?.
        /// </summary>
        internal static string MSG46 {
            get {
                return ResourceManager.GetString("MSG46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This record was modified by others, please retry!.
        /// </summary>
        internal static string MSG47 {
            get {
                return ResourceManager.GetString("MSG47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This kneading command cannot end the lot!.
        /// </summary>
        internal static string MSG48 {
            get {
                return ResourceManager.GetString("MSG48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This kneading command lot end Ok!.
        /// </summary>
        internal static string MSG49 {
            get {
                return ResourceManager.GetString("MSG49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More detail line cannot be selected, Ok?.
        /// </summary>
        internal static string MSG5 {
            get {
                return ResourceManager.GetString("MSG5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input tablet line does not match the tablet line in database!.
        /// </summary>
        internal static string MSG50 {
            get {
                return ResourceManager.GetString("MSG50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve the next pallet?.
        /// </summary>
        internal static string MSG51 {
            get {
                return ResourceManager.GetString("MSG51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you make sure to delete the product data about this pallet?.
        /// </summary>
        internal static string MSG52 {
            get {
                return ResourceManager.GetString("MSG52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelf no. error!.
        /// </summary>
        internal static string MSG53 {
            get {
                return ResourceManager.GetString("MSG53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;From location&quot; is bigger than &quot;To location&quot;!.
        /// </summary>
        internal static string MSG54 {
            get {
                return ResourceManager.GetString("MSG54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is out of range!.
        /// </summary>
        internal static string MSG55 {
            get {
                return ResourceManager.GetString("MSG55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to re-store?.
        /// </summary>
        internal static string MSG56 {
            get {
                return ResourceManager.GetString("MSG56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully!.
        /// </summary>
        internal static string MSG57 {
            get {
                return ResourceManager.GetString("MSG57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This product is duplicated by other details!.
        /// </summary>
        internal static string MSG6 {
            get {
                return ResourceManager.GetString("MSG6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A message is being received, please wait!.
        /// </summary>
        internal static string MSG7 {
            get {
                return ResourceManager.GetString("MSG7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conveyor status error!.
        /// </summary>
        internal static string MSG8 {
            get {
                return ResourceManager.GetString("MSG8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse status error!.
        /// </summary>
        internal static string MSG9 {
            get {
                return ResourceManager.GetString("MSG9", resourceCulture);
            }
        }
    }
}
