//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TabletisingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TabletisingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TabletisingResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find relative record in the Database..
        /// </summary>
        internal static string MSG1 {
            get {
                return ResourceManager.GetString("MSG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container has been taken out, tablet command cannot change..
        /// </summary>
        internal static string MSG11 {
            get {
                return ResourceManager.GetString("MSG11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This product has been selected..
        /// </summary>
        internal static string MSG12 {
            get {
                return ResourceManager.GetString("MSG12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total no. of commands cannot exceed 5..
        /// </summary>
        internal static string MSG14 {
            get {
                return ResourceManager.GetString("MSG14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yield Rate is zero..
        /// </summary>
        internal static string MSG15 {
            get {
                return ResourceManager.GetString("MSG15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container has been taken out, tablet command cannot change..
        /// </summary>
        internal static string MSG16 {
            get {
                return ResourceManager.GetString("MSG16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to add or update these Tabletising Commands?.
        /// </summary>
        internal static string MSG17 {
            get {
                return ResourceManager.GetString("MSG17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The used pre-product quantity is less than total quantity, add the remainder to the last item?.
        /// </summary>
        internal static string MSG18 {
            get {
                return ResourceManager.GetString("MSG18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The used pre-product quantity is more than total quantity..
        /// </summary>
        internal static string MSG19 {
            get {
                return ResourceManager.GetString("MSG19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This lot has not been completed..
        /// </summary>
        internal static string MSG20 {
            get {
                return ResourceManager.GetString("MSG20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to continue?.
        /// </summary>
        internal static string MSG21 {
            get {
                return ResourceManager.GetString("MSG21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to start?.
        /// </summary>
        internal static string MSG22 {
            get {
                return ResourceManager.GetString("MSG22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are left pre-product in warehouse yet. Ready to end the Tabletising Command?.
        /// </summary>
        internal static string MSG23 {
            get {
                return ResourceManager.GetString("MSG23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to end the Tabletising Command?.
        /// </summary>
        internal static string MSG24 {
            get {
                return ResourceManager.GetString("MSG24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack Quantity must be more than zero.
        /// </summary>
        internal static string MSG25 {
            get {
                return ResourceManager.GetString("MSG25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is out of range..
        /// </summary>
        internal static string MSG26 {
            get {
                return ResourceManager.GetString("MSG26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraction cannot be more than the packing unit..
        /// </summary>
        internal static string MSG27 {
            get {
                return ResourceManager.GetString("MSG27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplementary material is not enough..
        /// </summary>
        internal static string MSG28 {
            get {
                return ResourceManager.GetString("MSG28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to print?.
        /// </summary>
        internal static string MSG29 {
            get {
                return ResourceManager.GetString("MSG29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same record exists in database..
        /// </summary>
        internal static string MSG3 {
            get {
                return ResourceManager.GetString("MSG3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack quantity must be more than zero..
        /// </summary>
        internal static string MSG30 {
            get {
                return ResourceManager.GetString("MSG30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to set container?.
        /// </summary>
        internal static string MSG31 {
            get {
                return ResourceManager.GetString("MSG31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The charging container number is more than retrieved container amount.
        /// </summary>
        internal static string MSG32 {
            get {
                return ResourceManager.GetString("MSG32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully!.
        /// </summary>
        internal static string MSG33 {
            get {
                return ResourceManager.GetString("MSG33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add at least one record..
        /// </summary>
        internal static string MSG4 {
            get {
                return ResourceManager.GetString("MSG4", resourceCulture);
            }
        }
    }
}
