//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HttpMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HttpMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KCSG.Core.Resources.HttpMessages", typeof(HttpMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO_EMPTY_LOCATION_AVAILABLE_IN_WAREHOUSE.
        /// </summary>
        public static string EmptyLocationNotAvailable {
            get {
                return ResourceManager.GetString("EmptyLocationNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INPUT_TABLET_NOTMATCH_DATABASE.
        /// </summary>
        public static string InputTabletNotMatchDatabase {
            get {
                return ResourceManager.GetString("InputTabletNotMatchDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_INSERT_TX47.
        /// </summary>
        public static string InsertNotSucces {
            get {
                return ResourceManager.GetString("InsertNotSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_CONVEYOR_STATUS.
        /// </summary>
        public static string InvalidConveyorStatus {
            get {
                return ResourceManager.GetString("InvalidConveyorStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_DEVICE_AVAILABILITY.
        /// </summary>
        public static string InvalidDeviceAvailability {
            get {
                return ResourceManager.GetString("InvalidDeviceAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_KNEADING_COMMAND.
        /// </summary>
        public static string InvalidKneadingCommand {
            get {
                return ResourceManager.GetString("InvalidKneadingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_MATERIAL_SHELF_STATUS.
        /// </summary>
        public static string InvalidMaterialShelfStatus {
            get {
                return ResourceManager.GetString("InvalidMaterialShelfStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_MATERIAL_STATUS.
        /// </summary>
        public static string InvalidMaterialStatus {
            get {
                return ResourceManager.GetString("InvalidMaterialStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_PALLET_NO.
        /// </summary>
        public static string InvalidPalletNo {
            get {
                return ResourceManager.GetString("InvalidPalletNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_PRODUCT_SHELF_STATUS.
        /// </summary>
        public static string InvalidProductShelfStatus {
            get {
                return ResourceManager.GetString("InvalidProductShelfStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_SHELF_NO.
        /// </summary>
        public static string InvalidShelfNo {
            get {
                return ResourceManager.GetString("InvalidShelfNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_WAREHOUSE_STATUS.
        /// </summary>
        public static string InvalidWarehouseStatus {
            get {
                return ResourceManager.GetString("InvalidWarehouseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MATCHED_PALLET_NOT_FOUND.
        /// </summary>
        public static string MatchedPalletNotFound {
            get {
                return ResourceManager.GetString("MatchedPalletNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO_CORRESPONDING_IN_DATABASE.
        /// </summary>
        public static string NoCorrespondingInTheDatabase {
            get {
                return ResourceManager.GetString("NoCorrespondingInTheDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NoCorrespondingInTheDatabase1 {
            get {
                return ResourceManager.GetString("NoCorrespondingInTheDatabase1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECORD_BEING_MODIFIED.
        /// </summary>
        public static string RecordIsBeingModified {
            get {
                return ResourceManager.GetString("RecordIsBeingModified", resourceCulture);
            }
        }
    }
}
