//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealtimeConnection
    {
        public int Id { get; set; }
        public string Index { get; set; }
        public string TerminalNo { get; set; }
        public System.DateTime Joined { get; set; }
    }
}
