//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Te80_Env_Mesp
    {
        public string F80_Type { get; set; }
        public int F80_Id { get; set; }
        public string F80_Name { get; set; }
        public string F80_Humidity { get; set; }
        public Nullable<System.DateTime> F80_D_From { get; set; }
        public Nullable<System.DateTime> F80_D_To { get; set; }
        public Nullable<double> F80_T_Usl { get; set; }
        public Nullable<double> F80_T_Lsl { get; set; }
        public Nullable<double> F80_T_Ucl { get; set; }
        public Nullable<double> F80_T_Lcl { get; set; }
        public Nullable<double> F80_T_Mean { get; set; }
        public Nullable<double> F80_T_Sigma { get; set; }
        public Nullable<double> F80_T_Cp { get; set; }
        public Nullable<double> F80_T_Cpk { get; set; }
        public Nullable<double> F80_T_Range { get; set; }
        public Nullable<double> F80_H_Usl { get; set; }
        public Nullable<double> F80_H_Lsl { get; set; }
        public Nullable<double> F80_H_Ucl { get; set; }
        public Nullable<double> F80_H_Lcl { get; set; }
        public Nullable<double> F80_H_Mean { get; set; }
        public Nullable<double> F80_H_Sigma { get; set; }
        public Nullable<double> F80_H_Cp { get; set; }
        public Nullable<double> F80_H_Cpk { get; set; }
        public Nullable<double> F80_H_Range { get; set; }
        public Nullable<double> F80_T_Dis_Up { get; set; }
        public Nullable<double> F80_T_Dis_Lo { get; set; }
        public Nullable<double> F80_T_Scale { get; set; }
        public Nullable<double> F80_T_Cal_Up { get; set; }
        public Nullable<double> F80_T_Cal_Lo { get; set; }
        public Nullable<double> F80_H_Dis_Up { get; set; }
        public Nullable<double> F80_H_Dis_Lo { get; set; }
        public Nullable<double> F80_H_Scale { get; set; }
        public Nullable<double> F80_H_Cal_Up { get; set; }
        public Nullable<double> F80_H_Cal_Lo { get; set; }
    }
}
