//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Te81_Env_Temp
    {
        public int ID { get; set; }
        public System.DateTime F81_Env_Time { get; set; }
        public int F81_Id { get; set; }
        public Nullable<double> F81_Temp { get; set; }
        public Nullable<double> F81_Humidity { get; set; }
    }
}
