//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Te82_Env_Aval
    {
        public int ID { get; set; }
        public System.DateTime F82_Env_Time { get; set; }
        public int F82_Id { get; set; }
        public string F82_Status { get; set; }
    }
}
