//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Te83_Env_Else
    {
        public int ID { get; set; }
        public System.DateTime F83_Env_Time { get; set; }
        public int F83_Id { get; set; }
        public Nullable<double> F83_Value { get; set; }
    }
}
