//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Te84_Env_Lot
    {
        public int F84_Id { get; set; }
        public string F84_ProductCode { get; set; }
        public System.DateTime F84_S_Time { get; set; }
        public string F84_ProductLotNo { get; set; }
        public Nullable<double> F84_Temp { get; set; }
    }
}
