//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Te85_Env_Prod
    {
        public string F85_Code { get; set; }
        public string F85_Type { get; set; }
        public Nullable<int> F85_Id { get; set; }
        public Nullable<System.DateTime> F85_From { get; set; }
        public Nullable<System.DateTime> F85_To { get; set; }
        public Nullable<double> F85_M_Usl { get; set; }
        public Nullable<double> F85_M_Lsl { get; set; }
        public Nullable<double> F85_M_Ucl { get; set; }
        public Nullable<double> F85_M_Lcl { get; set; }
        public Nullable<double> F85_R_Usl { get; set; }
        public Nullable<double> F85_R_Lsl { get; set; }
        public Nullable<double> F85_T_High { get; set; }
        public Nullable<double> F85_T_Low { get; set; }
        public Nullable<double> F85_T_Ucl { get; set; }
        public Nullable<double> F85_T_Lcl { get; set; }
        public Nullable<double> F85_T_Cpk { get; set; }
        public Nullable<double> F85_T_Cp { get; set; }
        public Nullable<double> F85_T_Range { get; set; }
        public Nullable<double> F85_T_Mean { get; set; }
        public Nullable<double> F85_T_Sigma { get; set; }
        public Nullable<double> F85_R_High { get; set; }
        public Nullable<double> F85_R_Low { get; set; }
        public Nullable<double> F85_R_Ucl { get; set; }
        public Nullable<double> F85_R_Lcl { get; set; }
        public Nullable<double> F85_R_Cpk { get; set; }
        public Nullable<double> F85_R_Cp { get; set; }
        public Nullable<double> F85_R_Range { get; set; }
        public Nullable<double> F85_R_Mean { get; set; }
        public Nullable<double> F85_R_Sigma { get; set; }
        public Nullable<int> F85_No_Lot { get; set; }
    }
}
