//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class te90_env_tmp
    {
        public System.DateTime S_FLD_DTM { get; set; }
        public int S_FLD_ID { get; set; }
        public Nullable<double> S_FLD_DATA { get; set; }
        public Nullable<double> S_FLD_MEAN { get; set; }
        public Nullable<double> S_FLD_UPPER { get; set; }
        public Nullable<double> S_FLD_LOWER { get; set; }
        public string S_FLD_LOT { get; set; }
    }
}
