//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH60_MtrWhsCmdHst
    {
        public string F60_CommandNo { get; set; }
        public string F60_CmdSeqNo { get; set; }
        public string F60_CommandType { get; set; }
        public string F60_StrRtrType { get; set; }
        public string F60_Status { get; set; }
        public int F60_Priority { get; set; }
        public string F60_PalletNo { get; set; }
        public string F60_From { get; set; }
        public string F60_To { get; set; }
        public Nullable<System.DateTime> F60_CommandSendDate { get; set; }
        public Nullable<System.DateTime> F60_CommandEndDate { get; set; }
        public string F60_TerminalNo { get; set; }
        public string F60_PictureNo { get; set; }
        public string F60_AbnormalCode { get; set; }
        public Nullable<int> F60_RetryCount { get; set; }
        public System.DateTime F60_AddDate { get; set; }
        public System.DateTime F60_UpdateDate { get; set; }
        public Nullable<int> F60_UpdateCount { get; set; }
        public int F60_ID { get; set; }
    }
}
