//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH61_MtrStgRtrHst
    {
        public string F61_MaterialCode { get; set; }
        public string F61_MaterialLotNo { get; set; }
        public string F61_PalletNo { get; set; }
        public System.DateTime F61_StgRtrDate { get; set; }
        public string F61_PrcPdtNo { get; set; }
        public string F61_PrtDvrNo { get; set; }
        public string F61_From { get; set; }
        public string F61_To { get; set; }
        public string F61_StgRtrCls { get; set; }
        public string F61_TerminalNo { get; set; }
        public double F61_Amount { get; set; }
        public System.DateTime F61_AddDate { get; set; }
        public System.DateTime F61_UpdateDate { get; set; }
    }
}
