//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH62_KndCmdMsrSndHst
    {
        public string F62_KndCmdNo { get; set; }
        public string F62_PrePdtLotNo { get; set; }
        public string F62_PrePdtCode { get; set; }
        public string F62_Status { get; set; }
        public string F62_Priority { get; set; }
        public string F62_MsrSndCls { get; set; }
        public string F62_TerminalNo { get; set; }
        public string F62_PictureNo { get; set; }
        public string F62_AbnormalCode { get; set; }
    }
}
