//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH63_PrePdtWhsCmdHst
    {
        public string F63_CommandNo { get; set; }
        public string F63_CmdSeqNo { get; set; }
        public string F63_CommandType { get; set; }
        public string F63_StrRtrType { get; set; }
        public string F63_Status { get; set; }
        public string F63_ContainerNo { get; set; }
        public string F63_ContainerCode { get; set; }
        public int F63_Priority { get; set; }
        public string F63_From { get; set; }
        public string F63_To { get; set; }
        public Nullable<System.DateTime> F63_CommandSendDate { get; set; }
        public Nullable<System.DateTime> F63_CommandEndDate { get; set; }
        public string F63_TerminalNo { get; set; }
        public string F63_PictureNo { get; set; }
        public string F63_AbnormalCode { get; set; }
        public Nullable<int> F63_RetryCount { get; set; }
        public System.DateTime F63_AddDate { get; set; }
        public System.DateTime F63_UpdateDate { get; set; }
        public Nullable<int> F63_UpdateCount { get; set; }
        public int F63_ID { get; set; }
    }
}
