//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH64_PrePdtStgRtrHst
    {
        public string F64_PreProductCode { get; set; }
        public string F64_PreProductLotNo { get; set; }
        public string F64_ContainerCode { get; set; }
        public System.DateTime F64_StgRtrDate { get; set; }
        public string F64_ContainerNo { get; set; }
        public int F64_ContainerSeqNo { get; set; }
        public string F64_From { get; set; }
        public string F64_To { get; set; }
        public string F64_StgRtrCls { get; set; }
        public string F64_TerminalNo { get; set; }
        public double F64_Amount { get; set; }
        public System.DateTime F64_AddDate { get; set; }
        public System.DateTime F64_UpdateDate { get; set; }
    }
}
