//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH65_PdtStgRtrHst
    {
        public string F65_ProductCode { get; set; }
        public string F65_PrePdtLotNo { get; set; }
        public string F65_PalletNo { get; set; }
        public System.DateTime F65_StgRtrDate { get; set; }
        public string F65_ProductLotNo { get; set; }
        public string F65_From { get; set; }
        public string F65_To { get; set; }
        public string F65_StgRtrCls { get; set; }
        public string F65_TerminalNo { get; set; }
        public double F65_Amount { get; set; }
        public System.DateTime F65_AddDate { get; set; }
        public System.DateTime F65_UpdateDate { get; set; }
    }
}
