//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH66_PdtWhsCmdHst
    {
        public string F66_CommandNo { get; set; }
        public string F66_CmdSeqNo { get; set; }
        public string F66_CommandType { get; set; }
        public string F66_StrRtrType { get; set; }
        public string F66_Status { get; set; }
        public int F66_Priority { get; set; }
        public string F66_PalletNo { get; set; }
        public string F66_From { get; set; }
        public string F66_To { get; set; }
        public Nullable<System.DateTime> F66_CommandSendDate { get; set; }
        public Nullable<System.DateTime> F66_CommandEndDate { get; set; }
        public string F66_TerminalNo { get; set; }
        public string F66_PictureNo { get; set; }
        public string F66_AbnormalCode { get; set; }
        public Nullable<int> F66_RetryCount { get; set; }
        public System.DateTime F66_AddDate { get; set; }
        public System.DateTime F66_UpdateDate { get; set; }
        public Nullable<int> F66_UpdateCount { get; set; }
        public int F66_ID { get; set; }
    }
}
