//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH67_CrfHst
    {
        public string F67_ProductCode { get; set; }
        public string F67_PrePdtLotNo { get; set; }
        public string F67_ProductFlg { get; set; }
        public double F67_Amount { get; set; }
        public string F67_ProductLotNo { get; set; }
        public string F67_CertificationFlag { get; set; }
        public System.DateTime F67_CertificationDate { get; set; }
        public System.DateTime F67_AddDate { get; set; }
        public System.DateTime F67_UpdateDate { get; set; }
        public Nullable<int> F67_UpdateCount { get; set; }
    }
}
