//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH68_MtrMsrSndCmdHst
    {
        public string F68_TerminalNo { get; set; }
        public System.DateTime F68_AddDate { get; set; }
        public string F68_MsrMacCls { get; set; }
        public string F68_CommandType { get; set; }
        public string F68_Status { get; set; }
        public string F68_Priority { get; set; }
        public string F68_MasterCode { get; set; }
        public string F68_PictureNo { get; set; }
        public string F68_AbnormalCode { get; set; }
    }
}
