//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH69_MtrRtrMsrSndCmdHst
    {
        public System.DateTime F69_MtrRtrDate { get; set; }
        public string F69_PalletNo { get; set; }
        public string F69_MaterialCode { get; set; }
        public string F69_MsrMacClass { get; set; }
        public string F69_TerminalNo { get; set; }
        public string F69_PictureNo { get; set; }
        public string F69_Status { get; set; }
        public string F69_Priority { get; set; }
        public string F69_MtrLotNo1 { get; set; }
        public string F69_MtrLotNo2 { get; set; }
        public string F69_MtrLotNo3 { get; set; }
        public string F69_MtrLotNo4 { get; set; }
        public string F69_MtrLotNo5 { get; set; }
        public Nullable<double> F69_Amount1 { get; set; }
        public Nullable<double> F69_Amount2 { get; set; }
        public Nullable<double> F69_Amount3 { get; set; }
        public Nullable<double> F69_Amount4 { get; set; }
        public Nullable<double> F69_Amount5 { get; set; }
        public string F69_AbnormalCode { get; set; }
    }
}
