//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH70_PdtShipHst
    {
        public string F70_ShipCommandNo { get; set; }
        public string F70_PalletNo { get; set; }
        public string F70_PrePdtLotNo { get; set; }
        public string F70_ProductCode { get; set; }
        public string F70_ShelfNo { get; set; }
        public string F70_ProductLotNo { get; set; }
        public double F70_ShippedAmount { get; set; }
        public System.DateTime F70_AddDate { get; set; }
        public System.DateTime F70_UpdateDate { get; set; }
        public Nullable<int> F70_UpdateCount { get; set; }
    }
}
