//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM01_Material
    {
        public string F01_MaterialCode { get; set; }
        public string F01_SupplierCode { get; set; }
        public string F01_MaterialDsp { get; set; }
        public Nullable<double> F01_EMP { get; set; }
        public string F01_ModifyClass { get; set; }
        public string F01_Point { get; set; }
        public string F01_Unit { get; set; }
        public string F01_EntrustedClass { get; set; }
        public double F01_PackingUnit { get; set; }
        public Nullable<double> F01_Price { get; set; }
        public string F01_Department { get; set; }
        public string F01_LiquidClass { get; set; }
        public string F01_FactoryClass { get; set; }
        public string F01_RtrPosCls { get; set; }
        public string F01_MsrMacSndFlg { get; set; }
        public string F01_State { get; set; }
        public string F01_Color { get; set; }
        public System.DateTime F01_AddDate { get; set; }
        public System.DateTime F01_UpdateDate { get; set; }
        public Nullable<int> F01_UpdateCount { get; set; }
    }
}
