//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM02_PrePdtMkp
    {
        public string F02_PreProductCode { get; set; }
        public string F02_MaterialCode { get; set; }
        public string F02_ThrawSeqNo { get; set; }
        public double F02_3FLayinAmount { get; set; }
        public double F02_4FLayinAmount { get; set; }
        public int F02_LayinPriority { get; set; }
        public int F02_WeighingMethod { get; set; }
        public int F02_MilingFlag1 { get; set; }
        public int F02_MilingFlag2 { get; set; }
        public string F02_LoadPosition { get; set; }
        public string F02_PotSeqNo { get; set; }
        public string F02_MsrSeqNo { get; set; }
        public string F02_Addtive { get; set; }
        public System.DateTime F02_AddDate { get; set; }
        public System.DateTime F02_UpdateDate { get; set; }
        public Nullable<int> F02_UpdateCount { get; set; }
        public Nullable<bool> F02_IsDraft { get; set; }
    }
}
