//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM03_PreProduct
    {
        public string F03_PreProductCode { get; set; }
        public string F03_PreProductName { get; set; }
        public int F03_BatchLot { get; set; }
        public string F03_KneadingLine { get; set; }
        public double F03_YieldRate { get; set; }
        public double F03_AllMtrAmtPerBth { get; set; }
        public string F03_Point { get; set; }
        public Nullable<System.DateTime> F03_MixDate1 { get; set; }
        public Nullable<System.DateTime> F03_MixDate2 { get; set; }
        public Nullable<System.DateTime> F03_MixDate3 { get; set; }
        public Nullable<System.DateTime> F03_TmpRetTime { get; set; }
        public string F03_ContainerType { get; set; }
        public string F03_LowTmpClass { get; set; }
        public string F03_ColorClass { get; set; }
        public int F03_LotNoEnd { get; set; }
        public string F03_MixMode { get; set; }
        public System.DateTime F03_AddDate { get; set; }
        public System.DateTime F03_UpdateDate { get; set; }
        public Nullable<int> F03_UpdateCount { get; set; }
    }
}
