//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM04_Supplier
    {
        public string F04_SupplierCode { get; set; }
        public string F04_SupplierName { get; set; }
        public string F04_Address1 { get; set; }
        public string F04_Address2 { get; set; }
        public string F04_Address3 { get; set; }
        public string F04_Tel1 { get; set; }
        public string F04_Tel2 { get; set; }
        public string F04_Tel3 { get; set; }
        public string F04_Fax1 { get; set; }
        public string F04_Fax2 { get; set; }
        public string F04_Fax3 { get; set; }
        public int F04_MaxLoadAmount { get; set; }
        public System.DateTime F04_AddDate { get; set; }
        public System.DateTime F04_UpdateDate { get; set; }
        public Nullable<int> F04_UpdateCount { get; set; }
    }
}
