//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM06_Terminal
    {
        public string F06_TerminalNo { get; set; }
        public string F06_TerminalName { get; set; }
        public string F06_TermPos { get; set; }
        public string F06_TabletLine { get; set; }
        public string F06_ContinueFlag { get; set; }
        public string F06_OtherFlag { get; set; }
        public int F06_IPAddress1 { get; set; }
        public int F06_IPAddress2 { get; set; }
        public int F06_IPAddress3 { get; set; }
        public int F06_IPAddress4 { get; set; }
        public System.DateTime F06_AddDate { get; set; }
        public System.DateTime F06_UpdateDate { get; set; }
        public Nullable<int> F06_UpdateCount { get; set; }
    }
}
