//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM07_Calendar
    {
        public System.DateTime F07_Date { get; set; }
        public string F07_HolidayFlag { get; set; }
        public string F07_SunSatDayFlag { get; set; }
        public string F07_Description { get; set; }
        public System.DateTime F07_AddDate { get; set; }
        public System.DateTime F07_UpdateDate { get; set; }
        public Nullable<int> F07_UpdateCount { get; set; }
    }
}
