//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM08_Container
    {
        public string F08_ContainerType { get; set; }
        public string F08_ContainerName { get; set; }
        public System.DateTime F08_AddDate { get; set; }
        public System.DateTime F08_UpdateDate { get; set; }
        public Nullable<int> F08_UpdateCount { get; set; }
    }
}
