//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM09_Product
    {
        public string F09_ProductCode { get; set; }
        public string F09_ProductDesp { get; set; }
        public string F09_TabletType { get; set; }
        public string F09_TabletSize { get; set; }
        public string F09_TabletSize2 { get; set; }
        public int F09_NeedTime { get; set; }
        public double F09_TabletAmount { get; set; }
        public int F09_KneadingTime { get; set; }
        public string F09_EndUserCode { get; set; }
        public double F09_YieldRate { get; set; }
        public string F09_Factor { get; set; }
        public double F09_StdStkMtn { get; set; }
        public double F09_PackingUnit { get; set; }
        public string F09_PreProductCode { get; set; }
        public string F09_Unit { get; set; }
        public string F09_ValidPeriod { get; set; }
        public string F09_InsideLabelClass { get; set; }
        public string F09_LowTmpCls { get; set; }
        public System.DateTime F09_AddDate { get; set; }
        public System.DateTime F09_UpdateDate { get; set; }
        public Nullable<int> F09_UpdateCount { get; set; }
        public string F09_Label { get; set; }
    }
}
