//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM10_EndUsr
    {
        public string F10_EndUserCode { get; set; }
        public string F10_EndUserName { get; set; }
        public string F10_Address1 { get; set; }
        public string F10_Address2 { get; set; }
        public string F10_Address3 { get; set; }
        public string F10_Tel1 { get; set; }
        public string F10_Tel2 { get; set; }
        public string F10_Tel3 { get; set; }
        public string F10_Fax1 { get; set; }
        public string F10_Fax2 { get; set; }
        public string F10_Fax3 { get; set; }
        public System.DateTime F10_AddDate { get; set; }
        public System.DateTime F10_UpdateDate { get; set; }
        public Nullable<int> F10_UpdateCount { get; set; }
    }
}
