//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM11_PckMtr
    {
        public string F11_ProductCode { get; set; }
        public string F11_SubMaterialCode { get; set; }
        public double F11_Amount { get; set; }
        public string F11_Unit { get; set; }
        public System.DateTime F11_AddDate { get; set; }
        public System.DateTime F11_UpdateDate { get; set; }
        public Nullable<int> F11_UpdateCount { get; set; }
    }
}
