//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM13_Function
    {
        public string F13_PictureNo { get; set; }
        public string F13_PswdLevel { get; set; }
        public string F13_AccessCtrlFlag { get; set; }
        public string F13_UserNumCtrlFlag { get; set; }
        public int F13_MaxUser { get; set; }
        public int F13_UsingCount { get; set; }
    }
}
