//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM14_Device
    {
        public string F14_DeviceCode { get; set; }
        public string F14_DeviceName { get; set; }
        public string F14_UsePermitClass { get; set; }
        public string F14_DeviceStatus { get; set; }
        public Nullable<int> F14_IPAddress1 { get; set; }
        public Nullable<int> F14_IPAddress2 { get; set; }
        public Nullable<int> F14_IPAddress3 { get; set; }
        public Nullable<int> F14_IPAddress4 { get; set; }
        public string F14_DeviceMode { get; set; }
        public string F14_CSNo { get; set; }
        public System.DateTime F14_AddDate { get; set; }
        public System.DateTime F14_UpdateDate { get; set; }
        public Nullable<int> F14_UpdateCount { get; set; }
        public Nullable<int> F14_CSNumber { get; set; }
    }
}
