//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM15_SubMaterial
    {
        public string F15_SubMaterialCode { get; set; }
        public string F15_SupplierCode { get; set; }
        public string F15_MaterialDsp { get; set; }
        public Nullable<double> F15_EMP { get; set; }
        public string F15_ModifyClass { get; set; }
        public string F15_Point { get; set; }
        public string F15_Unit { get; set; }
        public string F15_EntrustedClass { get; set; }
        public double F15_PackingUnit { get; set; }
        public Nullable<double> F15_Price { get; set; }
        public string F15_Department { get; set; }
        public string F15_State { get; set; }
        public string F15_Color { get; set; }
        public System.DateTime F15_AddDate { get; set; }
        public System.DateTime F15_UpdateDate { get; set; }
        public Nullable<int> F15_UpdateCount { get; set; }
    }
}
