//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM17_TermStatus
    {
        public string F17_TermNo { get; set; }
        public string F17_InUsePictureNo { get; set; }
        public Nullable<System.DateTime> F17_LastRequest { get; set; }
    }
}
