//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX30_Reception
    {
        public string F30_PrcOrdNo { get; set; }
        public string F30_PrtDvrNo { get; set; }
        public string F30_MaterialCode { get; set; }
        public double F30_ExpectAmount { get; set; }
        public Nullable<System.DateTime> F30_ExpectDate { get; set; }
        public double F30_StoragedAmount { get; set; }
        public string F30_AcceptClass { get; set; }
        public System.DateTime F30_AddDate { get; set; }
        public System.DateTime F30_UpdateDate { get; set; }
        public Nullable<int> F30_UpdateCount { get; set; }
    }
}
