//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX32_MtrShf
    {
        public string F32_PalletNo { get; set; }
        public string F32_PrcOrdNo { get; set; }
        public string F32_PrtDvrNo { get; set; }
        public string F32_MegaMsrMacSndEndFlg { get; set; }
        public string F32_GnrlMsrMacSndEndFlg { get; set; }
        public Nullable<System.DateTime> F32_StorageDate { get; set; }
        public Nullable<System.DateTime> F32_ReStorageDate { get; set; }
        public Nullable<System.DateTime> F32_RetrievalDate { get; set; }
        public System.DateTime F32_AddDate { get; set; }
        public System.DateTime F32_UpdateDate { get; set; }
        public Nullable<int> F32_UpdateCount { get; set; }
    }
}
