//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX33_MtrShfStk
    {
        public string F33_PalletNo { get; set; }
        public string F33_MaterialCode { get; set; }
        public string F33_MaterialLotNo { get; set; }
        public double F33_Amount { get; set; }
        public string F33_StockFlag { get; set; }
        public System.DateTime F33_AddDate { get; set; }
        public System.DateTime F33_UpdateDate { get; set; }
    }
}
