//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX34_MtrWhsCmd
    {
        public string F34_CommandNo { get; set; }
        public string F34_CmdSeqNo { get; set; }
        public string F34_CommandType { get; set; }
        public string F34_StrRtrType { get; set; }
        public string F34_Status { get; set; }
        public int F34_Priority { get; set; }
        public string F34_PalletNo { get; set; }
        public string F34_From { get; set; }
        public string F34_To { get; set; }
        public Nullable<System.DateTime> F34_CommandSendDate { get; set; }
        public Nullable<System.DateTime> F34_CommandEndDate { get; set; }
        public string F34_TerminalNo { get; set; }
        public string F34_PictureNo { get; set; }
        public string F34_AbnormalCode { get; set; }
        public Nullable<int> F34_RetryCount { get; set; }
        public System.DateTime F34_AddDate { get; set; }
        public System.DateTime F34_UpdateDate { get; set; }
        public Nullable<int> F34_UpdateCount { get; set; }
    }
}
