//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX37_PrePdtShfSts
    {
        public string F37_ShelfRow { get; set; }
        public string F37_ShelfBay { get; set; }
        public string F37_ShelfLevel { get; set; }
        public string F37_ContainerCode { get; set; }
        public string F37_ContainerNo { get; set; }
        public string F37_ShelfStatus { get; set; }
        public string F37_ShelfType { get; set; }
        public string F37_LowTmpCls { get; set; }
        public Nullable<int> F37_CmnShfAgnOrd { get; set; }
        public Nullable<int> F37_LowTmpShfAgnOrd { get; set; }
        public string F37_TerminalNo { get; set; }
        public string F37_ContainerType { get; set; }
        public string F37_StockTakingFlag { get; set; }
        public Nullable<System.DateTime> F37_StorageDate { get; set; }
        public Nullable<System.DateTime> F37_RetrievalDate { get; set; }
        public System.DateTime F37_AddDate { get; set; }
        public System.DateTime F37_UpdateDate { get; set; }
        public Nullable<int> F37_UpdateCount { get; set; }
    }
}
