//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX39_PdtPln
    {
        public string F39_PreProductCode { get; set; }
        public System.DateTime F39_KndEptBgnDate { get; set; }
        public string F39_KneadingLine { get; set; }
        public string F39_KndCmdNo { get; set; }
        public int F39_PrePdtLotAmt { get; set; }
        public string F39_Status { get; set; }
        public string F39_ColorClass { get; set; }
        public string F39_StartLotNo { get; set; }
        public int F39_EndLotAmont { get; set; }
        public System.DateTime F39_AddDate { get; set; }
        public System.DateTime F39_UpdateDate { get; set; }
        public Nullable<int> F39_UpdateCount { get; set; }
    }
}
