//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX40_PdtShfStk
    {
        public string F40_PalletNo { get; set; }
        public string F40_PrePdtLotNo { get; set; }
        public string F40_ProductCode { get; set; }
        public string F40_ProductLotNo { get; set; }
        public string F40_StockFlag { get; set; }
        public int F40_PackageAmount { get; set; }
        public double F40_Fraction { get; set; }
        public double F40_Amount { get; set; }
        public System.DateTime F40_TabletingEndDate { get; set; }
        public double F40_ShippedAmount { get; set; }
        public string F40_ShipCommandNo { get; set; }
        public Nullable<double> F40_AssignAmount { get; set; }
        public string F40_CertificationFlg { get; set; }
        public Nullable<System.DateTime> F40_CertificationDate { get; set; }
        public System.DateTime F40_AddDate { get; set; }
        public System.DateTime F40_UpdateDate { get; set; }
        public Nullable<int> F40_UpdateCount { get; set; }
    }
}
