//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX41_TbtCmd
    {
        public string F41_KndCmdNo { get; set; }
        public string F41_PrePdtLotNo { get; set; }
        public string F41_TabletLine { get; set; }
        public string F41_PreproductCode { get; set; }
        public string F41_Status { get; set; }
        public int F41_TblCntAmt { get; set; }
        public int F41_RtrEndCntAmt { get; set; }
        public int F41_ChgCntAmt { get; set; }
        public Nullable<System.DateTime> F41_TbtBgnDate { get; set; }
        public Nullable<System.DateTime> F41_TbtEndDate { get; set; }
        public System.DateTime F41_AddDate { get; set; }
        public System.DateTime F41_UpdateDate { get; set; }
        public Nullable<int> F41_UpdateCount { get; set; }
    }
}
