//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX42_KndCmd
    {
        public string F42_KndCmdNo { get; set; }
        public string F42_PrePdtLotNo { get; set; }
        public string F42_PreProductCode { get; set; }
        public System.DateTime F42_KndEptBgnDate { get; set; }
        public string F42_OutSideClass { get; set; }
        public string F42_Status { get; set; }
        public double F42_ThrowAmount { get; set; }
        public double F42_NeedAmount { get; set; }
        public Nullable<System.DateTime> F42_TrwBgnDate { get; set; }
        public Nullable<System.DateTime> F42_TrwEndDate { get; set; }
        public Nullable<System.DateTime> F42_KndBgnDate { get; set; }
        public Nullable<System.DateTime> F42_KndEndDate { get; set; }
        public int F42_StgCtnAmt { get; set; }
        public int F42_BatchEndAmount { get; set; }
        public int F42_KndCmdBookNo { get; set; }
        public int F42_LotSeqNo { get; set; }
        public int F42_CommandSeqNo { get; set; }
        public string F42_MtrRtrFlg { get; set; }
        public System.DateTime F42_AddDate { get; set; }
        public System.DateTime F42_UpdateDate { get; set; }
        public Nullable<int> F42_UpdateCount { get; set; }
    }
}
