//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX43_KndRcd
    {
        public string F43_KndCmdNo { get; set; }
        public string F43_PrePdtLotNo { get; set; }
        public int F43_BatchSeqNo { get; set; }
        public string F43_MaterialCode { get; set; }
        public string F43_MaterialLotNo { get; set; }
        public double F43_LayinginAmount { get; set; }
        public Nullable<System.DateTime> F43_MsrMacSndDate { get; set; }
        public Nullable<System.DateTime> F43_BthBgnDate { get; set; }
        public Nullable<System.DateTime> F43_BthEndDate { get; set; }
        public System.DateTime F43_AddDate { get; set; }
        public System.DateTime F43_UpdateDate { get; set; }
        public Nullable<int> F43_UpdateCount { get; set; }
    }
}
