//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX44_ShippingPlan
    {
        public string F44_ShipCommandNo { get; set; }
        public string F44_ProductLotNo { get; set; }
        public string F44_ProductCode { get; set; }
        public double F44_ShpRqtAmt { get; set; }
        public double F44_ShippedAmount { get; set; }
        public Nullable<System.DateTime> F44_DeliveryDate { get; set; }
        public string F44_EndUserCode { get; set; }
        public string F44_Status { get; set; }
        public System.DateTime F44_AddDate { get; set; }
        public System.DateTime F44_UpdateDate { get; set; }
        public Nullable<int> F44_UpdateCount { get; set; }
    }
}
