//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX45_ShipCommand
    {
        public string F45_ShipCommandNo { get; set; }
        public Nullable<System.DateTime> F45_ShipDate { get; set; }
        public double F45_ShipAmount { get; set; }
        public double F45_ShippedAmount { get; set; }
        public System.DateTime F45_AddDate { get; set; }
        public System.DateTime F45_UpdateDate { get; set; }
        public Nullable<int> F45_UpdateCount { get; set; }
    }
}
