//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX46_SupMtrStk
    {
        public string F46_SubMaterialCode { get; set; }
        public string F46_Comment { get; set; }
        public System.DateTime F46_StorageDate { get; set; }
        public double F46_Amount { get; set; }
        public System.DateTime F46_AddDate { get; set; }
        public System.DateTime F46_UpdateDate { get; set; }
        public Nullable<int> F46_UpdateCount { get; set; }
    }
}
