//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX47_PdtWhsCmd
    {
        public string F47_CommandNo { get; set; }
        public string F47_CmdSeqNo { get; set; }
        public string F47_CommandType { get; set; }
        public string F47_StrRtrType { get; set; }
        public string F47_Status { get; set; }
        public int F47_Priority { get; set; }
        public string F47_PalletNo { get; set; }
        public string F47_From { get; set; }
        public string F47_To { get; set; }
        public Nullable<System.DateTime> F47_CommandSendDate { get; set; }
        public Nullable<System.DateTime> F47_CommandEndDate { get; set; }
        public string F47_TerminalNo { get; set; }
        public string F47_PictureNo { get; set; }
        public string F47_AbnormalCode { get; set; }
        public Nullable<int> F47_RetryCount { get; set; }
        public System.DateTime F47_AddDate { get; set; }
        public System.DateTime F47_UpdateDate { get; set; }
        public Nullable<int> F47_UpdateCount { get; set; }
    }
}
