//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX48_NoManage
    {
        public string F48_SystemId { get; set; }
        public int F48_KndCmdBookNo { get; set; }
        public int F48_MegaKndCmdNo { get; set; }
        public int F48_GnrKndCmdNo { get; set; }
        public int F48_OutKndCmdNo { get; set; }
        public int F48_KneadSheefNo { get; set; }
        public int F48_CnrKndCmdNo { get; set; }
        public int F48_MtrWhsCmdNo { get; set; }
        public int F48_PrePdtWhsCmdNo { get; set; }
        public int F48_PdtWhsCmdNo { get; set; }
        public int F48_OutPlanPdtCmdNo { get; set; }
        public System.DateTime F48_AddDate { get; set; }
        public System.DateTime F48_UpdateDate { get; set; }
        public Nullable<int> F48_UpdateCount { get; set; }
    }
}
