//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX49_PrePdtShfStk
    {
        public string F49_ContainerCode { get; set; }
        public string F49_KndCmdNo { get; set; }
        public string F49_ContainerNo { get; set; }
        public string F49_PreProductCode { get; set; }
        public string F49_PreProductLotNo { get; set; }
        public double F49_Amount { get; set; }
        public string F49_ShelfStatus { get; set; }
        public Nullable<System.DateTime> F49_StorageDate { get; set; }
        public Nullable<System.DateTime> F49_RetrievalDate { get; set; }
        public int F49_ContainerSeqNo { get; set; }
        public System.DateTime F49_AddDate { get; set; }
        public System.DateTime F49_UpdateDate { get; set; }
        public Nullable<int> F49_UpdateCount { get; set; }
    }
}
