//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX50_PrePdtWhsCmd
    {
        public string F50_CommandNo { get; set; }
        public string F50_CmdSeqNo { get; set; }
        public string F50_CommandType { get; set; }
        public string F50_StrRtrType { get; set; }
        public string F50_Status { get; set; }
        public string F50_ContainerNo { get; set; }
        public string F50_ContainerCode { get; set; }
        public int F50_Priority { get; set; }
        public string F50_From { get; set; }
        public string F50_To { get; set; }
        public Nullable<System.DateTime> F50_CommandSendDate { get; set; }
        public Nullable<System.DateTime> F50_CommandEndDate { get; set; }
        public string F50_TerminalNo { get; set; }
        public string F50_PictureNo { get; set; }
        public string F50_AbnormalCode { get; set; }
        public Nullable<int> F50_RetryCount { get; set; }
        public string F50_LotEndFlg { get; set; }
        public System.DateTime F50_AddDate { get; set; }
        public System.DateTime F50_UpdateDate { get; set; }
        public Nullable<int> F50_UpdateCount { get; set; }
    }
}
