//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX52_MtrMsrSndCmd
    {
        public string F52_TerminalNo { get; set; }
        public System.DateTime F52_AddDate { get; set; }
        public string F52_MsrMacCls { get; set; }
        public string F52_CommandType { get; set; }
        public string F52_Status { get; set; }
        public string F52_Priority { get; set; }
        public string F52_MasterCode { get; set; }
        public string F52_PictureNo { get; set; }
        public string F52_AbnormalCode { get; set; }
        public System.DateTime F52_UpdateDate { get; set; }
        public Nullable<int> F52_UpdateCount { get; set; }
    }
}
