//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX53_OutSidePrePdtStk
    {
        public string F53_PalletNo { get; set; }
        public string F53_OutSidePrePdtCode { get; set; }
        public string F53_OutSidePrePdtLotNo { get; set; }
        public string F53_KndCmdNo { get; set; }
        public int F53_PalletSeqNo { get; set; }
        public double F53_Amount { get; set; }
        public string F53_StockFlag { get; set; }
        public System.DateTime F53_AddDate { get; set; }
        public System.DateTime F53_UpdateDate { get; set; }
        public Nullable<int> F53_UpdateCount { get; set; }
    }
}
