//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX54_MtrRtrMsrSndCmd
    {
        public System.DateTime F54_MtrRtrDate { get; set; }
        public string F54_PalletNo { get; set; }
        public string F54_MaterialCode { get; set; }
        public string F54_MsrMacClass { get; set; }
        public string F54_TerminalNo { get; set; }
        public string F54_PictureNo { get; set; }
        public string F54_Status { get; set; }
        public string F54_Priority { get; set; }
        public string F54_MtrLotNo1 { get; set; }
        public string F54_MtrLotNo2 { get; set; }
        public string F54_MtrLotNo3 { get; set; }
        public string F54_MtrLotNo4 { get; set; }
        public string F54_MtrLotNo5 { get; set; }
        public Nullable<double> F54_Amount1 { get; set; }
        public Nullable<double> F54_Amount2 { get; set; }
        public Nullable<double> F54_Amount3 { get; set; }
        public Nullable<double> F54_Amount4 { get; set; }
        public Nullable<double> F54_Amount5 { get; set; }
        public string F54_AbnormalCode { get; set; }
        public System.DateTime F54_AddDate { get; set; }
        public System.DateTime F54_UpdateDate { get; set; }
        public Nullable<int> F54_UpdateCount { get; set; }
    }
}
