//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX55_KndCmdMsrSnd
    {
        public string F55_KndCmdNo { get; set; }
        public string F55_PrePdtLotNo { get; set; }
        public string F55_PrePdtCode { get; set; }
        public string F55_Status { get; set; }
        public string F55_Priority { get; set; }
        public string F55_MsrSndCls { get; set; }
        public string F55_TerminalNo { get; set; }
        public string F55_PictureNo { get; set; }
        public string F55_AbnormalCode { get; set; }
        public System.DateTime F55_AddDate { get; set; }
        public System.DateTime F55_UpdateDate { get; set; }
        public Nullable<int> F55_UpdateCount { get; set; }
    }
}
