//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX56_TbtPdt
    {
        public string F56_KndCmdNo { get; set; }
        public string F56_PrePdtLotNo { get; set; }
        public string F56_ProductCode { get; set; }
        public string F56_ProductLotNo { get; set; }
        public string F56_Status { get; set; }
        public double F56_TbtCmdAmt { get; set; }
        public double F56_TbtCmdEndPackAmt { get; set; }
        public double F56_TbtCmdEndFrtAmt { get; set; }
        public double F56_TbtCmdEndAmt { get; set; }
        public double F56_StorageAmt { get; set; }
        public Nullable<System.DateTime> F56_TbtBgnDate { get; set; }
        public Nullable<System.DateTime> F56_TbtEndDate { get; set; }
        public string F56_CertificationFlag { get; set; }
        public Nullable<System.DateTime> F56_CertificationDate { get; set; }
        public Nullable<System.DateTime> F56_ShipDate { get; set; }
        public System.DateTime F56_AddDate { get; set; }
        public System.DateTime F56_UpdateDate { get; set; }
        public Nullable<int> F56_UpdateCount { get; set; }
    }
}
