//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX57_PdtShf
    {
        public string F57_PalletNo { get; set; }
        public Nullable<System.DateTime> F57_StorageDate { get; set; }
        public Nullable<System.DateTime> F57_ReStorageDate { get; set; }
        public Nullable<System.DateTime> F57_RetievalDate { get; set; }
        public string F57_OutFlg { get; set; }
        public System.DateTime F57_AddDate { get; set; }
        public System.DateTime F57_UpdateDate { get; set; }
        public Nullable<int> F57_UpdateCount { get; set; }
    }
}
