//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX58_OutPlanPdt
    {
        public string F58_PrePdtLotNo { get; set; }
        public string F58_ProductCode { get; set; }
        public string F58_PdtSeqNo { get; set; }
        public string F58_ProductLotNo { get; set; }
        public string F58_Status { get; set; }
        public double F58_TbtCmdEndPackAmt { get; set; }
        public double F58_TbtCmdEndFrtAmt { get; set; }
        public double F58_TbtCmdEndAmt { get; set; }
        public double F58_StorageAmt { get; set; }
        public Nullable<System.DateTime> F58_TbtEndDate { get; set; }
        public string F58_CertificationFlag { get; set; }
        public Nullable<System.DateTime> F58_CertificationDate { get; set; }
        public Nullable<System.DateTime> F58_ShipDate { get; set; }
        public System.DateTime F58_AddDate { get; set; }
        public System.DateTime F58_UpdateDate { get; set; }
        public Nullable<int> F58_UpdateCount { get; set; }
    }
}
