//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX93_ProductTotal
    {
        public System.DateTime F93_YearMonth { get; set; }
        public string F93_ProductCode { get; set; }
        public double F93_PrevRemainder { get; set; }
        public double F93_Received { get; set; }
        public double F93_Used { get; set; }
        public Nullable<System.DateTime> F93_AddDate { get; set; }
        public Nullable<System.DateTime> F93_UpdateDate { get; set; }
    }
}
