//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCSG.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX94_Prepdtplan
    {
        public System.DateTime F94_YearMonth { get; set; }
        public string F94_PrepdtCode { get; set; }
        public double F94_amount { get; set; }
        public Nullable<System.DateTime> F94_AddDate { get; set; }
        public Nullable<System.DateTime> F94_UpdateDate { get; set; }
    }
}
